# Тема “Вычисления с помощью Numpy”


## Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [ ]:
import numpy as np

In [20]:
a = np.array([[1,2,3,3,1],[6,8,11,10,7]])
mean_a = a.mean(axis=1)

In [21]:
mean_a

array([2. , 8.4])

In [24]:
print("Средние отклонения: {}".format(mean_a))

Средние квадратические отклонения: [2.  8.4]


## Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [37]:
a_centered = a.T - mean_a

In [40]:
print("Массив centered : \n {}".format(a_centered))

Массив centered : 
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


## Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [63]:
a_centered_sp = a_centered[:,1:2] * a_centered[:,:1]

In [64]:
a_centered_sp

array([[ 2.4],
       [-0. ],
       [ 2.6],
       [ 1.6],
       [ 1.4]])